### ISSUE TITLE
docker-tcp.socket fails: Socket service docker.service already active, refusing.

### ISSUE THREAD

**Issue by carmstrong** [coreos/coreos-vagrant#172]
```
● docker-tcp.socket - Docker Socket for the API
   Loaded: loaded (/etc/systemd/system/docker-tcp.socket; enabled)
   Active: inactive (dead)
   Listen: [::]:2375 (Stream)

Sep 30 18:51:56 docker-registry systemd[1]: Starting Docker Socket for the API.
Sep 30 18:51:56 docker-registry systemd[1]: Socket service docker.service already active, refusing.
Sep 30 18:51:56 docker-registry systemd[1]: Failed to listen on Docker Socket for the API.
Sep 30 18:56:06 docker-registry systemd[1]: Starting Docker Socket for the API.
Sep 30 18:56:06 docker-registry systemd[1]: Socket service docker.service already active, refusing.
Sep 30 18:56:06 docker-registry systemd[1]: Failed to listen on Docker Socket for the API.
```

This will start once we've disabled `docker.socket`, but that prevents anything on the machine from using Docker via the local socket. I haven't yet found a way for them both to run.

**Comment by crawford** [comment]
I was recently able to reproduce this issue. If I start both docker.socket and docker-tcp.socket before either accepts any connections, both come up fine. On the other hand, if I activate the docker.socket (e.g. `docker ps`) and _then_ start docker-tcp.socket, it fails with the above error.

**Comment by bcwaldon** [comment]
@carmstrong You can't start a socket file after it's corresponding service is already running. There are two ways to fix this:
1) add a ListenStream option to the builtin docker.socket using a drop-in in your cloud-config

```
#cloud-config
coreos:
    units:
      - name: docker.socket
        command: start
        drop-ins:
      - name: 30-ListenStream.conf
        content: |
          [Socket]
          ListenStream=127.0.0.1:2375
```

2) add the following options to docker.service

```
[Unit]
Requires=docker.socket
After=docker.socket
Requires=docker-tcp.socket
After=docker-tcp.socket
```

Option 1 is preferable, as it leaves you with a single socket file, making your problem effectively go away. Option 2 works because it forces all known sockets to start up if docker.service ever starts, but it sets up an inverted chain of dependencies that will cause more problems in the future.

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1362
