### ISSUE TITLE
Shared Folder doesn't work on Windows 7

### ISSUE THREAD

**Issue by flyisland** [coreos/coreos-vagrant#185]
vagrant: 1.6.5, Windows 7 sp1

after added `config.vm.synced_folder "D:/DevProjects/docker", "/dockerfiles"`, the `vagrant up` shows

```
No synced folder implementation is available for your synced folders!
Please consult the documentation to learn why this may be the case.
You may force a synced folder implementation by specifying a "type:"
option for the synced folders. Available synced folder implementations
are listed below.
```

At the same time, my other vagrant boxes(like `centos-6.5-x86_64`) work fine with the same shared folder.

**Comment by jaustinhughey** [comment]
I'm having a similar issue, and found this via Google search. How odd!

Vagrantfile (relevant parts):
```ruby
# Defaults for config options defined in CONFIG
$num_instances = 1
$instance_name_prefix = "core"
$update_channel = "stable"
$enable_serial_logging = false
$share_home = false
$vm_gui = false
$vm_memory = 1024
$vm_cpus = 1

# ... later on down the file ...

      # Uncomment below to enable NFS for sharing the host machine into the coreos-vagrant VM.
      config.vm.synced_folder ".", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']

      if $share_home
        config.vm.synced_folder ENV['HOME'], ENV['HOME'], id: "home", type: "nfs", :nfs => true, :mount_options => ['nolock,vers=3,udp']
      end
```

I'm getting the exact same error message that @flyisland is. So I tried forcing type: "nfs". I tried commenting the entire ```if $share_home``` block, thinking it was choking there somehow (nope). Neither option helped whatsoever.

Now the thing that makes this not work out of the box, @flyisland, is that the CoreOS image that Vagrant is downloading does NOT have virtualbox extensions enabled in the kernel. See this piece of Vagrantfile for that:

```ruby
  config.vm.provider :virtualbox do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in CoreOS, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end
```

So, don't check for guest additions, and don't bother turning on the VirtualBox filesystem (vboxsf). But your CentOS image obviously _does_ have that enabled, which is why it's working fine over there.

I'm going to try to implement this over rsync for now, but wow this is annoying. I would strongly recommend that all future deployed CoreOS images have VirtualBox extensions enabled and ready to go in the kernel.

**Comment by DJviolin** [comment]
When I enable config.vm.synced_folder line in the file and try vagrant up, the vagrant bootup will hangs. Stopping the boot sequence and nothing happens.

**Comment by dicato** [comment]
I'm seeing the same symptoms as @DJviolin on OSX with vagrant version 1.7.2 and virtualbox 4.3.22.

@bcwaldon I'm happy to make a new issue if you deem appropriate. A `vagrant up`  is hanging on:

```
==> core-01: Exporting NFS shared folders...
==> core-01: Preparing to edit /etc/exports. Administrator privileges will be required...
==> core-01: Mounting NFS shared folders...

```

**Comment by jmkgreen** [comment]
Vagrant does not support nfs on Windows. You must specify type: "smb" instead.

**Comment by gary-kupferle** [comment]
I tried several combinations of smb and couldn't get that to work. The best options I could think of were:

config.vm.synced_folder ".", "/home/core/share", type: "smb"
config.vm.synced_folder ".", "vagrant", type: "smb"

I'm new to coreOS and have basic knowledge of Vagrant. I may be missing something, particularly with coreOS. The second option above is pretty standard for Vagrant running on a Windows host according to what I've found (but feel free to enlighten).

**Comment by dpalomar** [comment]
I'm having similar issue on win8.1. This combination works for me:

        config.vm.synced_folder ".", "/home/core/share", id: "core",type:"smb", :smb=> true, :mount_options => ['nolock,vers=3,udp']

But I have found several issues:

1.  It's mandatory to run with windows admin privileges (I don't know why is neccessary to create a network device)
2.  After insert user/pass of windows and create the network unit the following error is shown:

        `Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o uid=`id -u core`,gid=`getent group core | cut -d: -f3`,nolock,vers=3,udp,sec=ntlm,u
sername=user,pass=PASSWORDHIDDEN //192.168.1.13/70815395828bdc5419399ade0bb121ee /home/core/share
mount -t cifs -o uid=`id -u core`,gid=`id -g core`,nolock,vers=3,udp,sec=ntlm,username=user,pass=PA
SSWORDHIDDEN //192.168.1.13/70815395828bdc5419399ade0bb121ee /home/core/share

The error output from the last command was:

mount: wrong fs type, bad option, bad superblock on //192.168.1.13/70815395828bdc5419399ade0bb121ee,

       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.`

**Comment by streamich** [comment]
Any solution how to share folder on Windows with CoreOS?

**Comment by demaniak** [comment]
Yeah, the smb trick did not work for me.

Nor did a simple `config.vm.synced_folder "src/", "/srv/website"` - which is probably because those pesky guest additions are not included in the CoreOS image.This is rather annoying, to say the least.

If I just want to get a zip archive on to the CoreOS VM, does anybody have a less painfull method at hand than uploading it somewhere, and then downloading it with curl?

**Comment by drasamsetti** [comment]
Is there anyway we can share folder from host (windows) to Vagrant - CoreOS (Guest) with the help of "config.vm.synced_folder" . I have tried all the possible ways.. 
NFS not supported by Windows
SMB and rsync options are facing challenges from "vboxsf"
error:
--------------------------------------------
"Failed to mount folders in Linux guest. This is usually because the "vboxsf" file system is not available. Please verify that the guest additions are properly installed in the guest and can work properly. The command attempted was:"
--------------------------------------------------

Can somebody tell me.. whether there is a any successful use case where this is issue resolved.
Appreciate your feedback in advance, pls respond asap. Thank you

**Comment by demaniak** [comment]
@drasamsetti as far as I know the only way to resolve this issue is to get the VB guest additions installed in the CoreOS base image.

I have not tried this, but it should be possible to spin up a clone of the CoreOS image, install the guest additions, then create a new Vagrant box from that image. However, I *ASSUME* the CoreOS guys have some good reason to not install the guest additions in their base image...

**Comment by drasamsetti** [comment]
tried this 
https://registry.hub.docker.com/u/yungsang/coreos-vboxguest/
but no breakthrough yet... :(

**Comment by drasamsetti** [comment]
seems... major tools.. like Docker, CoreOS, and Ansible are abandoning Windows as one of the Development Environment . i.e too sad..

**Comment by demaniak** [comment]
@drasamsetti - not so, for example http://www.opencontainers.org/

The problem here is with VirtualBox more than anything. Unfortunately, we are trying some cutting-edge stuff here, so there are bound to be problems. 
MS is apparently promising native docker support soon - we will see.

**Comment by langdead** [comment]
The same problem...
```
No synced folder implementation is available for your synced folders!
Please consult the documentation to learn why this may be the case.
You may force a synced folder implementation by specifying a "type:"
option for the synced folders. Available synced folder implementations
are listed below.

docker, nfs, rsync, smb, virtualbox
```

In config.rb, neither 
`$share_home=true`
nor 
`$shared_folders = {'d:/work' => '/home/core/work'}`
works.

And it makes no difference to comment or not following line in file Vagrantfile
```
      # Uncomment below to enable NFS for sharing the host machine into the coreos-vagrant VM.
      config.vm.synced_folder ".", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']
```

Thanks!

**Comment by jschott2** [comment]
The only option I found to work at this time is rsync.  See my notes below on testing all the types.
for install options on a windows 7 machine see the document in jschott2/coreos-vagrant "CoreOS-Vagrant-for-Windows-7-Documentation.docx" or use this branch.  Hacks are needed and are documented in this branch.

 I cannot get this to work under Windows 10.

	##########################################################################
	# This was found as an option to open a file share but it is for a single
	# linux machine instance.  nfs is also a non windows type
	##########################################################################
 	#config.vm.network "private_network", ip: "172.17.8.150"
	#config.vm.synced_folder ".", "/home/core/share", id: "core", :nfs => false,  :mount_options   => ['nolock,vers=3,udp']
	##########################################################################

# uses nfs does not work with windows 

      # Uncomment below to enable NFS for sharing the host machine into the coreos-vagrant VM.
      # config.vm.synced_folder "shared", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']
        #########################################################################
      	#config.vm.synced_folder "./shared", "/home/core/share", type: "nfs"
	##########################################################################
	# Windows users: NFS folders DO NOT WORK on Windows hosts.
	# Vagrant will ignore your request for NFS synced folders on Windows
	##########################################################################

# nfs does not work with windows

	##########################################################################
	# This option is not in the Vagrant documentation
	##########################################################################
      #config.vm.synced_folder "./shared", "/home/core/share", type: "docker"

# docker is not documented ?

	##########################################################################
	# using the VirtualBox provider, then VirtualBox shared folders are the 
	# default synced folder type.
	# These synced folders use the VirtualBox shared folder system to sync 
	# file changes from the guest to the host and vice versa.
	##########################################################################
      # config.vm.synced_folder "./shared", "/home/core/share", type: "virtualbox"

# virtualbox does not work

	##########################################################################
	# Windows only! SMB is currently only supported when the host machine is Windows.
	# The guest machine can be Windows or Linux
	##########################################################################
      #config.vm.synced_folder "./shared", "/home/core/share", type: "smb"
      # config.vm.synced_folder  "shared", "/home/core/share", type: "smb" :mount_options => ['nolock,vers=3,udp']

# smb does not work

	##########################################################################
	# On Windows, rsync installed with Cygwin or MinGW will be detected by Vagrant 
	# and works well.
	##########################################################################
	# config.vm.synced_folder "./shared", "/home/core/share", type: "rsync"
	# Results: "rsync: change_dir: "..." failed: No such file or directory (2)" 
	##########################################################################
	# config.vm.synced_folder "c:/Users/mylaptop/Documents/GitHub/coreos-vagrant/shared", "/home/core/share", type: "rsync"
	# Results: "the host path of the shared folder is missing: "...""
	##########################################################################
	# config.vm.synced_folder "/cygwin64/home/jwsii/shared/", "/home/core/share/", type: "rsync"

##############################################################################
# This configures a sync folder from the host to the guest.
##############################################################################  
	
	config.vm.synced_folder "./shared", "/home/core/share/", type: "rsync"

#Yea! rsync works but requires install of a package.  I used cygwin.


##############################################################################  
# Would like to do some things:
#  sync a folder from the guest to the host
#  have each guest folder be a unique name
##############################################################################  
# vm_name
puts "/home/core/" + vm_name + "/"
puts "C:/Users/<yourUserName>/Documents/GitHub/coreos-vagrant/share" + vm_name

	config.vm.synced_folder "./share" + vm_name, "/home/core/" + vm_name + "/", type: "rsync"

##############################################################################  
# This is set up for unix host only since it uses nfs
##############################################################################  
#      $shared_folders.each_with_index do |(host_folder, guest_folder), index|
#        config.vm.synced_folder host_folder.to_s, guest_folder.to_s, id: "core-share%02d" % index, nfs: true, mount_options: ['nolock,vers=3,udp']
#      end

**Comment by langdead** [comment]
@jschott2, thanks very much! 
Following your post, it still took me much time to do rsync from host to guest.
There are a different version of ssh in git on my host, it kept complaining until I changed the order of the bin paths in PATH.

To complement your post, `vagrant rsync-auto` in another windows cmd to trigger realtime update from host to guest.

But we still need to configure for a guest -> host rsync path... Annoying...

**Comment by langdead** [comment]
Em, I guess some of you might also get smb work by:

1st, `vagrant plugin install vagrant-vbguest --plugin-source http://rubygems.org`
2nd, using following line in `Vagrantfile`.
`config.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"`

DON'T add mount_options to smb line which will complains about some error.

With this configuration, the folder is shared and synced from both side(host->guest, guest->host).
God bless us!

**Comment by DJviolin** [comment]
Shared folders worked for me with this Vagrant Plugin:
https://github.com/winnfsd/vagrant-winnfsd

However my final solution was to NOT use Vagrant at all! Seriously, Vagrant not offering any more than just pre-configuring a Virutalbox environment to use with working shared folders. However, if you want to move your site to production, like on a DigitalOcean droplet, you need to know how to pre-configure your environment with cloud-config, etc. Exactly what you do when you create a fresh install CoreOS on a bare-metal Virtualbox VM. Backups? You can do that with Virtualbox snapshots. Shared folders? Well, that's a bummer, but you create an SFTP access and you use FileZilla to access it. Exactly what you will do in a real server environment. I have one SSH access into CoreOS and an other into my Debian inside a Docker container under the CoreOS host. If I want I can SFTP into both instances. Works like a charm. There's no any compatibility, stability issues that's created by only Vagrant.

**Comment by jmkgreen** [comment]
I do not think this ticket has anything to do with this project. The CoreOS folks are not going to fix this - the Vagrant folks might.

Isn't concentrating energy [here](https://github.com/mitchellh/vagrant/issues) going to be more useful?

FWIW I'm firing up LAMP Docker instances and volume mounting Windows 7 paths for source code changes - works fine for instance feedback. Uses Virtual Box under the hood.

**Comment by sjwoodard** [comment]
See here for a workaround for rsync in Vagrant 1.8+

https://github.com/mitchellh/vagrant/issues/6702

**Comment by jujes** [comment]
Same problem here...
Some news??

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1358
