### ISSUE TITLE
disk space is full, what should I do?

### ISSUE THREAD

**Issue by ablozhou** [coreos/coreos-vagrant#252]
core@core-01 ~ $ df -h
Filesystem                   Size  Used Avail Use% Mounted on
devtmpfs                     1.5G     0  1.5G   0% /dev
tmpfs                        1.5G     0  1.5G   0% /dev/shm
tmpfs                        1.5G  288K  1.5G   1% /run
tmpfs                        1.5G     0  1.5G   0% /sys/fs/cgroup
/dev/sda9                     16G   15G     0 100% /
/dev/sda3                    985M  350M  585M  38% /usr
tmpfs                        1.5G     0  1.5G   0% /media
tmpfs                        1.5G     0  1.5G   0% /tmp
/dev/sda6                    108M   88K   99M   1% /usr/share/oem

the coreos I run it by vagrant.
how to increase the disk space from host automatically?

**Comment by munkyboy** [comment]
`vagrant halt` the box. Use `VBoxManage modifyhd` to increase the drive.[reference here](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvdi)
Then `vagrant up` the box. CoreOS should automatically recognize the increased size in the /dev/sda9 partition.

**Comment by gxela** [comment]
can we have a box created for each different majorly prefered disk size, so to get up faster?

this dimension can be included in the box name and pulled in as per developer/project need.

20GB being the default and other can be selected
40GB
60GB
80GB
100GB
150GB
200GB
250GB
300GB
500GB
1TB

this can be part of your box build process and uploaded to the server that everyone uses to download this distribution from.

Linux users lover options, as do developers, so until there is no hacky way to do this manually or with a script then it would be preferred to get this out of the box with a simple flip of an option

By all means, you would be the first to do this, and therefore ahead of the game. thank you very much for such a great tool

**Comment by elkcip** [comment]
I am running out of disk space multiple times a day while experimenting with CoreOS. This is not a good "out of box" experience for new users, especially because it's not always obvious why "it's not working anymore". Lack of disk space can result in all sorts of errors that mention nothing of disk space until you dig a bit further. The workarounds I've seen are not something I want to inflict on my co-workers who just want a simple, working dev environment that they can easily destroy and recreate from scratch with 'vagrant up'.

**Comment by kveroneau** [comment]
munkyboy's solution sadly doesn't work, as the HDD image used by Vagrant is in VMDK format, here's the response I got:
0%...
Progress state: VBOX_E_NOT_SUPPORTED
VBoxManage: error: Resize medium operation for this format is not implemented yet!

Unacceptable!  Who in this day and age has tiny 20GB SATA disks!  The size should be extremely large, as this size is not allocated on the phyical disk on operating systems that support "Sparse Files", and I also don't believe that VirtualBox even uses Sparse Files, but rather it's own method to grow the actual size on disk as needed.

The least you could do, is provide a Packer file for us "experts" to use, so that we can rebuild the box ourselves to our own specifications.  I really don't like being treated like a goddamn child and having my hand held all the time.  We are all adult developers and/or sys admins here.  I don't see why CoreOS doesn't just give us a Packer JSON file so we can build our Vagrant box ourselves...

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1332
