### ISSUE TITLE
a syntax error.

### ISSUE THREAD

**Issue by wmydz1** [coreos/coreos-vagrant#286]
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/samchen/Documents/software/coreos-vagrant/Vagrantfile
Line number: 0
Message: Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 10 column 1

**Comment by crawford** [comment]
That file hasn't changed in months. Are you sure you don't have any local changes that are triggering this?

**Comment by kontact-chan** [comment]
I hit a similar issue:
[vancan@localhost coreos-vagrant]$ vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/vancan/programs/git-ws/coreos-vagrant/Vagrantfile
Line number: 0
Message: Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 46 column 3
[vancan@localhost coreos-vagrant]$
[vancan@localhost coreos-vagrant]$ vagrant -v
Vagrant 1.8.1
[vancan@localhost coreos-vagrant]$

**Comment by crawford** [comment]
Moved to https://github.com/coreos/bugs/issues/1319
